version: '3'

services:
  postgresql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: aftas
    ports:
      - "5432:5432"
    networks:
      - aftas-network
    restart: unless-stopped

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - postgresql
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/aftas
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - aftas-network
    restart: unless-stopped

  angular-app:
    build:
      context: C:/Users/adel/Desktop/Aftas-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - spring-app
    networks:
      - aftas-network
    restart: unless-stopped

networks:
  aftas-network:
    driver: bridge
